In [4]:
import numpy as np

# Khởi tạo node và element tấm

In [108]:
# Tao một hàm tạo node và element của phần tử tấm 
def node_element(num_elements,width,lenght ):
    matrix =  np.zeros([num_elements+1,num_elements+1])
    dem = 1
    for i in range(num_elements+1):
        for j in range(num_elements+1):
            matrix[i,j] = dem
            dem +=1

    node = np.zeros((num_elements+1)**2)
    for i in range(node.shape[0]):
        node[i] = i+1
    X = np.zeros((num_elements+1)**2)
    for i in range(X.shape[0]):
        X[i]=width*(i % (num_elements+1))/num_elements
    Y = np.zeros((num_elements+1)**2)
    for i in range(Y.shape[0]):
        Y[i]=lenght*(i // (num_elements+1))/num_elements
    Z = np.zeros((num_elements+1)**2)     
    
    matrix_node = np.zeros([(num_elements+1)**2,4])
    matrix_node[:,0]=node
    matrix_node[:,1]=X
    matrix_node[:,2]=Y
    matrix_node[:,3]=Z
    
    matrix_ele = np.zeros(4)
    ele = np.zeros(4)

    for i in range(num_elements):
        for j in range(num_elements):
            ele[0] = matrix[i,j]
            ele[1] = matrix[i+1,j] 
            ele[2] = matrix[i+1,j+1] 
            ele[3] = matrix[i,j+1] 
            matrix_ele = np.vstack((matrix_ele, ele))
       
                 
    matrix_ele = np.delete(matrix_ele,0,axis=0)
    num_ele = np.zeros([num_elements**2,1])
    for i in range(num_ele.shape[0]):
        num_ele[i,:]=i+1
    matrix_ele = np.concatenate((num_ele, matrix_ele), axis=1)  
    return matrix_node,  matrix_ele

In [87]:
a = np.zeros([5**2,1])
print(a)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [116]:
a , b =  node_element(10,1,1)
print(b)
print(a)


[[  1.   1.  12.  13.   2.]
 [  2.   2.  13.  14.   3.]
 [  3.   3.  14.  15.   4.]
 [  4.   4.  15.  16.   5.]
 [  5.   5.  16.  17.   6.]
 [  6.   6.  17.  18.   7.]
 [  7.   7.  18.  19.   8.]
 [  8.   8.  19.  20.   9.]
 [  9.   9.  20.  21.  10.]
 [ 10.  10.  21.  22.  11.]
 [ 11.  12.  23.  24.  13.]
 [ 12.  13.  24.  25.  14.]
 [ 13.  14.  25.  26.  15.]
 [ 14.  15.  26.  27.  16.]
 [ 15.  16.  27.  28.  17.]
 [ 16.  17.  28.  29.  18.]
 [ 17.  18.  29.  30.  19.]
 [ 18.  19.  30.  31.  20.]
 [ 19.  20.  31.  32.  21.]
 [ 20.  21.  32.  33.  22.]
 [ 21.  23.  34.  35.  24.]
 [ 22.  24.  35.  36.  25.]
 [ 23.  25.  36.  37.  26.]
 [ 24.  26.  37.  38.  27.]
 [ 25.  27.  38.  39.  28.]
 [ 26.  28.  39.  40.  29.]
 [ 27.  29.  40.  41.  30.]
 [ 28.  30.  41.  42.  31.]
 [ 29.  31.  42.  43.  32.]
 [ 30.  32.  43.  44.  33.]
 [ 31.  34.  45.  46.  35.]
 [ 32.  35.  46.  47.  36.]
 [ 33.  36.  47.  48.  37.]
 [ 34.  37.  48.  49.  38.]
 [ 35.  38.  49.  50.  39.]
 [ 36.  39.  50.  51

In [82]:
import numpy as np

# Ma trận ban đầu
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Cột mới cần thêm vào
new_column = np.array([[10],
                       [11],
                       [12]])

# Thêm cột mới vào ma trận
new_matrix = np.concatenate((matrix, new_column), axis=1)

print("Ma trận mới sau khi thêm cột:")
print(new_matrix)

Ma trận mới sau khi thêm cột:
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [84]:
num_elements = 5
width = 1cvvsvsv
lenght  = 1
a = np.zeros((num_elements+1)**2)
for i in range(a.shape[0]):
    a[i]=width*(i % (num_elements+1))/num_elements
b = np.zeros((num_elements+1)**2)
for i in range(a.shape[0]):
    b[i]=width*(i // (num_elements+1))/num_elements
print(a)
print(b)


[0.  0.2 0.4 0.6 0.8 1.  0.  0.2 0.4 0.6 0.8 1.  0.  0.2 0.4 0.6 0.8 1.
 0.  0.2 0.4 0.6 0.8 1.  0.  0.2 0.4 0.6 0.8 1.  0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.  0.  0.  0.  0.  0.2 0.2 0.2 0.2 0.2 0.2 0.4 0.4 0.4 0.4 0.4 0.4
 0.6 0.6 0.6 0.6 0.6 0.6 0.8 0.8 0.8 0.8 0.8 0.8 1.  1.  1.  1.  1.  1. ]


In [3]:
import numpy as np
for x in range(2, 30, 3):
  print(x)
El_1 = 10
ele_dam = np.array([[1,2,3,7,8,13],[50,50,50,50,50,50]])

a = El_1*(1-ele_dam[1,2]/100)
a

2
5
8
11
14
17
20
23
26
29


5.0